### PR TITLE
Add support for any repo, url or file upload

### PR DESCRIPTION
**Pull request by superdav42**
# Describe what your pull request addresses
#63 
- [ ] Support file upload
- [ ] Select any org and repo
- [ ] Any custom url

## Test Instructions

- [ ] Click add book
- [ ] Select any ord
- [ ] Choose any repo
- [ ] Choose any book
- [ ] Everything should work
- [ ] Also enter url with raw usfm
- [ ] It should work
- [ ] Saving should download the usfm
- [ ] Also upload a usfm file
- [ ] it should work
- [ ] Saving should download the usfm
- [ ] Choose Repo without write access
- [ ] Saving should download the usfm

For the curious it looks like this:
image

### CODE REVIEW

**Comment by mandolyte** [comment]
@superdav42 I love the look and the features. Some findings:
image
This happens before I even log in. So there are some timing issues. Perhaps you need to wait until authenticated?

**Comment by mandolyte** [comment]
Before I add any books, this shows up:
image
Again, I think you need wait on something... suspect the data is trying to be read before it is available.

**Comment by mandolyte** [comment]
When I supply these values to the dialog:
image

I am kicked out back to the login page. Here is the console:
image

**Comment by mandolyte** [comment]
I should add that if I use a URL to get that same book above, it works fine:
image

**Comment by mandolyte** [comment]
Downloading and uploading worked perfectly. Really nice work!

**Comment by superdav42** [comment]
@mandolyte All errors you encountered should be fixed now. Ready to review again.

**Pull request merged**
